/*
 * Copyright (C) 2024 Nickolas Martins
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package br.com.educreports.screens;

import br.com.educreports.controllers.StudentController;
import br.com.educreports.dao.ChildDAO;
import br.com.educreports.dao.TeacherDAO;
import br.com.educreports.models.Child;
import br.com.educreports.services.dateParser;
import br.com.educreports.services.checkUser;
import java.io.IOException;
import java.sql.*;
import java.awt.Image;
import java.text.ParseException;
import javax.imageio.ImageIO;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.JXDatePicker;

import javax.swing.table.DefaultTableModel;

/**
 * Student management screen
 *
 * @version 3.0
 * @author itsmenicky
 */
public class StudentView extends javax.swing.JInternalFrame {
    private StudentController controller;
    private TeacherDAO teacherDAO;
    private ChildDAO childDAO;

    /**
     * Creates new form StudentScreen
     */
    public StudentView() {
        initComponents();
        controller = new StudentController(this);
        teacherDAO = new TeacherDAO();
        childDAO = new ChildDAO();
    }

    /**
     * Function responsible for setting student txt fields and photo on the
     * interface
     */
    private void setStudentFields() throws SQLException {
        int set = tbStudent.getSelectedRow();
        txtRA.setText(tbStudent.getModel().getValueAt(set, 0).toString());
        txtName.setText(tbStudent.getModel().getValueAt(set, 1).toString());
        birthDate.setDate(dateParser.to_date(tbStudent.getModel().getValueAt(set, 2).toString()));
        txtClass.setText(tbStudent.getModel().getValueAt(set, 3).toString());
        System.out.println(tbStudent.getModel().getValueAt(set, 4).toString());
        ResultSet last_fields = childDAO.search_child(txtRA.getText());
        if(last_fields.next()){
            txtResponsible.setText(last_fields.getString("responsible"));
            txtPhone.setText(last_fields.getString("child_phone"));
            txtAddress.setText(last_fields.getString("address"));
            txtTeacherId.setText(last_fields.getString("teacher_id"));
            txtTeacherName.setText(last_fields.getString("teacher_name"));
            cbStatus.setSelectedItem(last_fields.getString("status"));
            lblPhoto.setIcon(controller.blob_to_icon(last_fields.getBlob("child_photo"), this.lblPhoto));
        }
    }

    /**
     * Function responsible for setting teacher text fields
     */
    private void setTeacherFields() {
        int set = tbTeacher.getSelectedRow();
        txtTeacherId.setText(tbTeacher.getModel().getValueAt(set, 0).toString());
        txtTeacherName.setText(tbTeacher.getModel().getValueAt(set, 1).toString());
    }

    /**
     * Function responsible for cleaning interface text fields, table and
     * setting default icon on photo area
     */
    private void clean_fields() {
        txtRA.setText(null);
        txtName.setText(null);
        birthDate.setDate(null);
        txtClass.setText(null);
        txtPhone.setText(null);
        txtResponsible.setText(null);
        txtAddress.setText(null);
        txtTeacherName.setText(null);
        txtTeacherId.setText(null);
        txtSearchStudent.setText(null);
        txtSearchTeacher.setText(null);
        lblPhoto.setIcon(new ImageIcon(getClass().getResource("/assets/camera-icon.png")));
        cbStatus.setSelectedIndex(0);
        ((DefaultTableModel) tbTeacher.getModel()).setRowCount(0);
        ((DefaultTableModel) tbStudent.getModel()).setRowCount(0);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTeacherId = new javax.swing.JTextField();
        txtRA = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        birthDate = new JXDatePicker();
        txtClass = new javax.swing.JTextField();
        txtResponsible = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtTeacherName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTeacher = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtSearchStudent = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSearchTeacher = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        btnAddStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alunos");

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 18, 53));
        jLabel1.setText("Alunos");

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setText("RA do aluno");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel4.setText("Data de nascimento");

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel5.setText("Turma");

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel6.setText("Nome do responsável");

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel7.setText("Contato");

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel8.setText("Endereço");

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel9.setText("Id do professor");

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel10.setText("Nome do professor");

        txtTeacherId.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtTeacherId.setEnabled(false);

        txtRA.setFont(new java.awt.Font("Montserrat", 0, 12));
        txtRA.setEnabled(false);// NOI18N

        txtName.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        birthDate.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        txtClass.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        txtResponsible.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        txtTeacherName.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtTeacherName.setEnabled(false);

        tbTeacher.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        tbTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTeacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTeacher);

        tbStudent.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tbStudentMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane2.setViewportView(tbStudent);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search-icon.png"))); // NOI18N
        jLabel11.setToolTipText("");

        txtSearchStudent.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtSearchStudent.setToolTipText("Pesquisar/Selecionar aluno");
        txtSearchStudent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchStudentKeyReleased(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search-icon.png"))); // NOI18N
        jLabel12.setToolTipText("");

        txtSearchTeacher.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtSearchTeacher.setToolTipText("Selecionar o professor");
        txtSearchTeacher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchTeacherKeyReleased(evt);
            }
        });

        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/camera-icon.png"))); // NOI18N
        lblPhoto.setToolTipText("Carregar foto");
        lblPhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    lblPhotoMouseClicked(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add-user2.png"))); // NOI18N
        btnAddStudent.setContentAreaFilled(false);
        btnAddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnAddStudentActionPerformed(evt);
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btnEditStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit-user2.png"))); // NOI18N
        btnEditStudent.setContentAreaFilled(false);
        btnEditStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditStudent.setEnabled(false);
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnEditStudentActionPerformed(evt);
                } catch (ParseException | IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel13.setText("* Todos os campos são obrigatórios");

        jLabel14.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel14.setText("Status");

        cbStatus.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Disabled" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(67, 67, 67)
                            .addComponent(jLabel13)
                            .addGap(84, 84, 84))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(txtTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(txtResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(txtRA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(6, 6, 6)
                                .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddStudent)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditStudent))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtSearchTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPhoto)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearchTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPhoto)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(txtRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4))
                            .addComponent(birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5))
                            .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6))
                            .addComponent(txtResponsible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7))
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8))
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9))
                            .addComponent(txtTeacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel10))
                            .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddStudent)
                            .addComponent(btnEditStudent))
                        .addGap(64, 64, 64))))
        );

        txtSearchStudent.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event responsible for calling photo upload function
     *
     * @param evt
     */
    private void lblPhotoMouseClicked(java.awt.event.MouseEvent evt) throws IOException {//GEN-FIRST:event_lblPhotoMouseClicked
        Image photo = ImageIO.read(controller.photoUpload()).getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_SMOOTH);
        lblPhoto.setIcon(new ImageIcon(photo));
        lblPhoto.updateUI();
    }//GEN-LAST:event_lblPhotoMouseClicked

    /**
     * Event responsible for calling search teacher function
     *
     * @param evt
     */
    private void txtSearchTeacherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTeacherKeyReleased
        tbTeacher.setModel(DbUtils.resultSetToTableModel(teacherDAO.search_teacher(txtTeacherName.getText())));
    }//GEN-LAST:event_txtSearchTeacherKeyReleased

    /**
     * Event responsible for calling set teacher fields function
     *
     * @param evt
     */
    private void tbTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTeacherMouseClicked
        setTeacherFields();
    }//GEN-LAST:event_tbTeacherMouseClicked

    /**
     * Event responsible for calling add student function
     *
     * @param evt
     */
    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) throws ParseException, IOException {//GEN-FIRST:event_btnAddStudentActionPerformed
        if(!checkUser.check_user() == true){
            JOptionPane.showMessageDialog(null, "Usuário inativo! Encerrando a sessão...");
            System.exit(0);
        }
        Child student = new Child(txtName.getText(), birthDate.getDate(), txtClass.getText(), controller.iconToBytes(lblPhoto.getIcon(), "png"), txtPhone.getText(), txtResponsible.getText(), txtAddress.getText(), txtTeacherName.getText(), Long.parseLong(txtTeacherId.getText()), "Active");
        controller.add_student(student);
        clean_fields();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    /**
     * Event responsible for calling search student function
     *
     * @param evt
     */
    private void txtSearchStudentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchStudentKeyReleased
        tbStudent.setModel(DbUtils.resultSetToTableModel(childDAO.search_child_to_table(txtSearchStudent.getText())));
    }//GEN-LAST:event_txtSearchStudentKeyReleased

    /**
     * Event responsible for, with the click on a table field, setting the
     * interface student text fields and configuring student buttons
     *
     * @param evt
     */
    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {//GEN-FIRST:event_tbStudentMouseClicked
        setStudentFields();
        btnAddStudent.setEnabled(false);
        btnEditStudent.setEnabled(true);
        txtName.setEnabled(false);
        birthDate.setEnabled(false);
    }//GEN-LAST:event_tbStudentMouseClicked

    /**
     * Event responsible for calling edit student function
     *
     * @param evt
     */
    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) throws ParseException, IOException {//GEN-FIRST:event_btnEditStudentActionPerformed
        if(!checkUser.check_user() == true){
            JOptionPane.showMessageDialog(null, "Usuário inativo! Encerrando a sessão...");
            System.exit(0);
        }
        int confirmation = JOptionPane.showConfirmDialog(null, "Confirma a atualização dos dados deste usuário?", "CONFIRMAÇÃO", JOptionPane.YES_NO_OPTION);
        Child student = new Child(txtName.getText(), birthDate.getDate(), txtClass.getText(), controller.iconToBytes(lblPhoto.getIcon(), "png"), txtPhone.getText(), txtResponsible.getText(), txtAddress.getText(), txtTeacherName.getText(), Long.parseLong(txtTeacherId.getText()), cbStatus.getSelectedItem().toString());
        if (confirmation == JOptionPane.YES_OPTION) {
            controller.edit_student(student, txtRA.getText(), lblPhoto.getIcon());
        }
        btnAddStudent.setEnabled(true);
        txtName.setEnabled(true);
        birthDate.setEnabled(true);
        clean_fields();
    }//GEN-LAST:event_btnEditStudentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTable tbTeacher;
    private javax.swing.JTextField txtAddress;
    private JXDatePicker birthDate;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRA;
    private javax.swing.JTextField txtResponsible;
    private javax.swing.JTextField txtSearchStudent;
    private javax.swing.JTextField txtSearchTeacher;
    private javax.swing.JTextField txtTeacherId;
    private javax.swing.JTextField txtTeacherName;
    // End of variables declaration//GEN-END:variables
}
